apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitorc-system
resources:
  - storage.yaml
  - ingress.yaml
  - runners.yaml
  - monitoring.yaml
  - logging.yaml
  - observability-stack.yaml
  - secrets-management.yaml
  - rancher-integration.yaml
  - gpu-support.yaml
  - gitorc-services.yaml