apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gitorc-barbican
spec:
  provider: barbican
  parameters:
    roleName: gitorc-operator
    secretID: replace-with-barbican-secret-id
  secretObjects:
    - secretName: gitorc-runtime-secrets
      type: Opaque
      data:
        - objectName: signing-private-key
          key: signing-private-key
        - objectName: ldap-bind-password
          key: ldap-bind-password