apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gitorc-ceph-rbd
  annotations:
    gitorc.io/role: artifacts
provisioner: csi.ceph.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  clusterID: gitorc-private-cloud
  pool: gitorc-artifacts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitorc-artifacts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: gitorc-ceph-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitorc-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: gitorc-ceph-rbd